/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    tenants: Tenant;
    memberships: Membership;
    properties: Property;
    'buyer-clients': BuyerClient;
    'media-assets': MediaAsset;
    'zonal-prices': ZonalPrice;
    conversations: Conversation;
    messages: Message;
    'whatsapp-instances': WhatsappInstance;
    'webhook-receipts': WebhookReceipt;
    'message-processing': MessageProcessing;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    memberships: MembershipsSelect<false> | MembershipsSelect<true>;
    properties: PropertiesSelect<false> | PropertiesSelect<true>;
    'buyer-clients': BuyerClientsSelect<false> | BuyerClientsSelect<true>;
    'media-assets': MediaAssetsSelect<false> | MediaAssetsSelect<true>;
    'zonal-prices': ZonalPricesSelect<false> | ZonalPricesSelect<true>;
    conversations: ConversationsSelect<false> | ConversationsSelect<true>;
    messages: MessagesSelect<false> | MessagesSelect<true>;
    'whatsapp-instances': WhatsappInstancesSelect<false> | WhatsappInstancesSelect<true>;
    'webhook-receipts': WebhookReceiptsSelect<false> | WebhookReceiptsSelect<true>;
    'message-processing': MessageProcessingSelect<false> | MessageProcessingSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'system-whatsapp': SystemWhatsapp;
  };
  globalsSelect: {
    'system-whatsapp': SystemWhatsappSelect<false> | SystemWhatsappSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  displayName?: string | null;
  /**
   * E.164 number this operator messages the platform line from. Identifies them on inbound.
   */
  whatsappPhone?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  slug: string;
  name: string;
  countryCode: string;
  publicChatKey: string;
  allowedOrigins?: string[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "memberships".
 */
export interface Membership {
  id: number;
  user: number | User;
  tenant: number | Tenant;
  role: 'owner' | 'member';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "properties".
 */
export interface Property {
  id: number;
  tenant: number | Tenant;
  reference: string;
  title: string;
  description?: string | null;
  price: number;
  currency: string;
  zone: string;
  pricingUnit: 'per_sqm' | 'total' | 'per_month';
  status: 'available' | 'reserved' | 'sold';
  images?: (number | MediaAsset)[] | null;
  mainImage?: (number | null) | MediaAsset;
  model3d?: (number | null) | MediaAsset;
  bedrooms?: number | null;
  bathrooms?: number | null;
  areaSqm?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-assets".
 */
export interface MediaAsset {
  id: number;
  tenant: number | Tenant;
  kind: 'image' | 'model-3d' | 'music' | 'video';
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "buyer-clients".
 */
export interface BuyerClient {
  id: number;
  tenant: number | Tenant;
  name: string;
  normalizedPhone?: string | null;
  email?: string | null;
  leadStatus: 'Cold' | 'Warm' | 'Hot';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "zonal-prices".
 */
export interface ZonalPrice {
  id: number;
  tenant: number | Tenant;
  zone: string;
  pricingUnit: 'per_sqm' | 'total' | 'per_month';
  amount: number;
  currency: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conversations".
 */
export interface Conversation {
  id: number;
  tenant: number | Tenant;
  client: number | BuyerClient;
  channel: 'whatsapp' | 'web-chat';
  channelThreadId: string;
  botPaused?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages".
 */
export interface Message {
  id: number;
  tenant: number | Tenant;
  conversation: number | Conversation;
  direction: 'inbound' | 'outbound';
  author: 'buyer' | 'ai' | 'human' | 'system';
  text: string;
  providerMessageId?: string | null;
  idempotencyKey: string;
  processingState?: ('pending' | 'processing' | 'completed' | 'failed' | 'skipped') | null;
  deliveryState?: ('pending' | 'sent' | 'failed' | 'unknown') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "whatsapp-instances".
 */
export interface WhatsappInstance {
  id: number;
  tenant: number | Tenant;
  instanceName: string;
  externalInstanceId?: string | null;
  connectionState: 'open' | 'connecting' | 'close';
  webhookConfigured?: boolean | null;
  /**
   * The line's own number, learned from the first event Evolution delivers for it.
   */
  connectedNumber?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "webhook-receipts".
 */
export interface WebhookReceipt {
  id: number;
  tenant: number | Tenant;
  instance: number | WhatsappInstance;
  providerEventKey: string;
  acceptedEventType: string;
  receivedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "message-processing".
 */
export interface MessageProcessing {
  id: number;
  tenant: number | Tenant;
  inboundMessage: number | Message;
  state: 'pending' | 'processing' | 'completed' | 'failed' | 'skipped';
  attempts?: number | null;
  safeError?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'memberships';
        value: number | Membership;
      } | null)
    | ({
        relationTo: 'properties';
        value: number | Property;
      } | null)
    | ({
        relationTo: 'buyer-clients';
        value: number | BuyerClient;
      } | null)
    | ({
        relationTo: 'media-assets';
        value: number | MediaAsset;
      } | null)
    | ({
        relationTo: 'zonal-prices';
        value: number | ZonalPrice;
      } | null)
    | ({
        relationTo: 'conversations';
        value: number | Conversation;
      } | null)
    | ({
        relationTo: 'messages';
        value: number | Message;
      } | null)
    | ({
        relationTo: 'whatsapp-instances';
        value: number | WhatsappInstance;
      } | null)
    | ({
        relationTo: 'webhook-receipts';
        value: number | WebhookReceipt;
      } | null)
    | ({
        relationTo: 'message-processing';
        value: number | MessageProcessing;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  displayName?: T;
  whatsappPhone?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  countryCode?: T;
  publicChatKey?: T;
  allowedOrigins?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "memberships_select".
 */
export interface MembershipsSelect<T extends boolean = true> {
  user?: T;
  tenant?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "properties_select".
 */
export interface PropertiesSelect<T extends boolean = true> {
  tenant?: T;
  reference?: T;
  title?: T;
  description?: T;
  price?: T;
  currency?: T;
  zone?: T;
  pricingUnit?: T;
  status?: T;
  images?: T;
  mainImage?: T;
  model3d?: T;
  bedrooms?: T;
  bathrooms?: T;
  areaSqm?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "buyer-clients_select".
 */
export interface BuyerClientsSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  normalizedPhone?: T;
  email?: T;
  leadStatus?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-assets_select".
 */
export interface MediaAssetsSelect<T extends boolean = true> {
  tenant?: T;
  kind?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "zonal-prices_select".
 */
export interface ZonalPricesSelect<T extends boolean = true> {
  tenant?: T;
  zone?: T;
  pricingUnit?: T;
  amount?: T;
  currency?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conversations_select".
 */
export interface ConversationsSelect<T extends boolean = true> {
  tenant?: T;
  client?: T;
  channel?: T;
  channelThreadId?: T;
  botPaused?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages_select".
 */
export interface MessagesSelect<T extends boolean = true> {
  tenant?: T;
  conversation?: T;
  direction?: T;
  author?: T;
  text?: T;
  providerMessageId?: T;
  idempotencyKey?: T;
  processingState?: T;
  deliveryState?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "whatsapp-instances_select".
 */
export interface WhatsappInstancesSelect<T extends boolean = true> {
  tenant?: T;
  instanceName?: T;
  externalInstanceId?: T;
  connectionState?: T;
  webhookConfigured?: T;
  connectedNumber?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "webhook-receipts_select".
 */
export interface WebhookReceiptsSelect<T extends boolean = true> {
  tenant?: T;
  instance?: T;
  providerEventKey?: T;
  acceptedEventType?: T;
  receivedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "message-processing_select".
 */
export interface MessageProcessingSelect<T extends boolean = true> {
  tenant?: T;
  inboundMessage?: T;
  state?: T;
  attempts?: T;
  safeError?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Provisioned from the CLI (pnpm wa:connect). Editing these values by hand will not re-pair the line.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "system-whatsapp".
 */
export interface SystemWhatsapp {
  id: number;
  /**
   * Evolution instance name. Convention: SYSTEM_<slug>.
   */
  instanceName?: string | null;
  externalInstanceId?: string | null;
  /**
   * Instance-scoped Evolution token returned at creation time.
   */
  apiKey?: string | null;
  connectionState?: ('open' | 'connecting' | 'close') | null;
  webhookConfigured?: boolean | null;
  /**
   * Owner JID reported by Evolution once the QR is scanned.
   */
  connectedNumber?: string | null;
  connectedAt?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "system-whatsapp_select".
 */
export interface SystemWhatsappSelect<T extends boolean = true> {
  instanceName?: T;
  externalInstanceId?: T;
  apiKey?: T;
  connectionState?: T;
  webhookConfigured?: T;
  connectedNumber?: T;
  connectedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}