/**
 * Inspects the local Evolution API stack and prints the credentials needed to
 * talk to it: the global API key (admin endpoints such as `/instance/create`)
 * and the per-instance token that messaging endpoints expect.
 *
 * Instance tokens are generated by Evolution itself, so they can only be read
 * back from a running container — this script is how you discover them after
 * `pnpm stack:up` and creating an instance.
 *
 * Run with: `pnpm evolution:keys`
 */
import { runScript } from './payload-script'

const REQUEST_TIMEOUT_MS = 10_000

interface EvolutionInstance {
  name: string
  id: string | null
  token: string | null
  connectionStatus: string
  ownerJid: string | null
  profileName: string | null
  integration: string | null
}

function readString(value: unknown): string | null {
  return typeof value === 'string' && value.length > 0 ? value : null
}

async function getJson(baseUrl: string, path: string, apiKey: string) {
  const controller = new AbortController()
  const timer = setTimeout(() => controller.abort(), REQUEST_TIMEOUT_MS)
  try {
    const response = await fetch(`${baseUrl}${path}`, {
      headers: { apikey: apiKey },
      signal: controller.signal,
    })
    let data: unknown = null
    try {
      data = await response.json()
    } catch {
      data = null
    }
    return { status: response.status, ok: response.ok, data }
  } finally {
    clearTimeout(timer)
  }
}

/**
 * Evolution v2.2+ returns flat instance objects; older builds nest them under an
 * `instance` key with different field names. Normalise both.
 */
function normalizeInstance(raw: unknown): EvolutionInstance | null {
  if (typeof raw !== 'object' || raw === null) return null
  const outer = raw as Record<string, unknown>
  const nested = (
    typeof outer.instance === 'object' && outer.instance !== null ? outer.instance : outer
  ) as Record<string, unknown>

  const name = readString(nested.name) ?? readString(nested.instanceName)
  if (!name) return null

  return {
    name,
    id: readString(nested.id) ?? readString(nested.instanceId),
    token: readString(nested.token) ?? readString(nested.apikey) ?? readString(nested.hash),
    connectionStatus:
      readString(nested.connectionStatus) ??
      readString(nested.status) ??
      readString(nested.state) ??
      'unknown',
    ownerJid: readString(nested.ownerJid) ?? readString(nested.owner) ?? readString(nested.number),
    profileName: readString(nested.profileName),
    integration: readString(nested.integration),
  }
}

runScript('Evolution key check', async () => {
  const baseUrl = (process.env.EVOLUTION_BASE_URL || '').replace(/\/$/, '')
  const globalKey = process.env.EVOLUTION_API_KEY || ''
  const prefix = process.env.EVOLUTION_INSTANCE_PREFIX || 'imno-agent'

  if (!baseUrl || !globalKey) {
    throw new Error('EVOLUTION_BASE_URL and EVOLUTION_API_KEY must be set in .env')
  }

  console.log('Evolution API')
  console.log(`  base URL   ${baseUrl}`)
  console.log(`  prefix     ${prefix}`)
  console.log(`  global key ${globalKey}`)
  console.log(`  webhook    ${process.env.EVOLUTION_WEBHOOK_URL || '(not set)'}`)

  console.log('\n→ Checking reachability…')
  let root
  try {
    root = await getJson(baseUrl, '/', globalKey)
  } catch (err) {
    const reason = err instanceof Error ? err.message : String(err)
    throw new Error(`cannot reach ${baseUrl} (${reason}). Is \`pnpm stack:up\` running?`)
  }
  const rootBody = (root.data ?? {}) as Record<string, unknown>
  console.log(`  ✓ reachable (version ${readString(rootBody.version) ?? 'unknown'})`)

  console.log('\n→ Fetching instances…')
  const { status, ok, data } = await getJson(baseUrl, '/instance/fetchInstances', globalKey)

  if (status === 401 || status === 403) {
    throw new Error(
      `Evolution rejected the global key (HTTP ${status}). EVOLUTION_API_KEY in .env must match ` +
        'AUTHENTICATION_API_KEY in the running container — restart with `pnpm stack:down && pnpm stack:up` after changing it.',
    )
  }
  if (!ok) {
    throw new Error(`fetchInstances returned HTTP ${status}`)
  }

  const instances = (Array.isArray(data) ? data : [])
    .map(normalizeInstance)
    .filter((instance): instance is EvolutionInstance => instance !== null)

  if (instances.length === 0) {
    console.log('  no instances exist yet.')
    console.log(
      `\nCreate one from the dashboard (Connect WhatsApp) or with:\n` +
        `  curl -X POST "${baseUrl}/instance/create" -H "apikey: ${globalKey}" \\\n` +
        `    -H "Content-Type: application/json" \\\n` +
        `    -d '{"instanceName":"${prefix}-demo-agency","integration":"WHATSAPP-BAILEYS","qrcode":true}'`,
    )
    return
  }

  console.log(`  ✓ ${instances.length} instance(s)\n`)
  for (const instance of instances) {
    console.log(`  ${instance.name}`)
    console.log(`    instance id   ${instance.id ?? '(none)'}`)
    console.log(`    api key       ${instance.token ?? '(none returned)'}`)
    console.log(`    connection    ${instance.connectionStatus}`)
    console.log(`    owner jid     ${instance.ownerJid ?? '(not connected)'}`)
    console.log(`    profile name  ${instance.profileName ?? '-'}`)
    console.log(`    integration   ${instance.integration ?? '-'}`)
    console.log('')
  }

  console.log('Use the global key for /instance/create and /instance/delete;')
  console.log('use an instance api key for messaging, chat, group and label endpoints.')
})
